### ISSUE TITLE
An error has occurred. Check your logs or contact the app author for clarification

### ISSUE THREAD

**Issue by Drosofriends** [ComputationalProteomics/OmicLoupe#13]
Hi I'm using OmicLoupe for my RNA-seq data but an error occurred: " An error has occurred. Check your logs or contact the app author for clarification"
How can this be solved? Is it a problem in my formatted tables?
thank you for your help!

**Comment by Jakob37** [comment]
Thanks for using OmicLoupe! Do you have a minimal design + data matrix that you would be able to share (that cause the same error)? Then we could test ourselves to better understand what is happening.

Also sending a ping to @flevander and @manszamore here who might know more.

**Comment by Drosofriends** [comment]
I have one simple question for first, what do sample values mean? Do you mean TPM or count values?
thank you for the support!

**Comment by Jakob37** [comment]
As OmicLoupe does not do any statistics, just visualizations, it should in principle be fine to use either. But TPM would probably be more informative for you, and closer to the use case where we have tested OmicLoupe (log transformed quantitative mass spectrometry-data, i.e. continuous normally distributed data).

It could be that it struggles with something in a count based dataset. If so, this sounds like a bug, and something we could investigate further.

Anyway, if you have only tested count values so far, it might be worth giving TPM a shot!

**Comment by Drosofriends** [comment]
I tired with TPM and everything works! I think the problem was also some missing dots in the sample values (i.e: 1530 instead of 1530.0 or 0 instead of 0.0)
thank for the help!

**Comment by Jakob37** [comment]
> I tired with TPM and everything works! I think the problem was also some missing dots in the sample values (i.e: 1530 instead of 1530.0 or 0 instead of 0.0) thank for the help!

OK, nice to hear!

Still looks like something we should look into. OmicLoupe should be able to handle count values (or at least communicate in a clearer way about the error). Thanks for noticing us!
