### ISSUE TITLE
Update or remove the Singularity instructions in the README

### ISSUE THREAD

**Issue by Jakob37** [ComputationalProteomics/OmicLoupe#8]
The page previously hosting the Singularity container seems to be down. This means that the instructions on how to retrieve Singularity is now outdated.

Also, I am not sure whether it works to run the previous command to retrieve the actual container. It would make more sense to leave this out for now, and find a new hosting option. Either using Singularity on some other site, or transferring the container to Docker instead.

**Comment by flevander** [comment]
Docker file added and singularity file removed n Pull request #10
